name: 'Semantic Release Action'
description: 'Semantic Release Action'
inputs:
  gpg-private-key:
    description: 'GPG Private Key'
    required: true
  gpg-passphrase:
    description: 'GPG passphrase'
    required: true
  bot-token:
    description: 'Bot token'
    required: true
  npm-token:
    description: 'NPM token'
    required: true
  git-author-name:
    description: 'GIT Author name'
    required: true
  git-author-email:
    description: 'GIT Author email'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 16
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ inputs.gpg-private-key }}
        passphrase: ${{ inputs.gpg-passphrase }}
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Install dependencies
      run: npm ci
    - name: Install semantic-release plugins
      run: npm i @semantic-release/changelog @semantic-release/git @semantic-release/exec replace semantic-release-config-cog
    - name: Release
      env:
        GITHUB_TOKEN: ${{ inputs.bot-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
        GIT_AUTHOR_NAME: ${{ inputs.git-author-name }}
        GIT_AUTHOR_EMAIL: ${{ inputs.git-author-email }}
        GIT_COMMITTER_NAME:  ${{ inputs.git-author-name }}
        GIT_COMMITTER_EMAIL:  ${{ inputs.git-author-email }}
      run: npx semantic-release
